apiVersion: v1
kind: Service
metadata:
  name: example-homepage
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 4173
  selector:
    app: example-homepage
  type: LoadBalancer
